---
- name: restart grafana
  service:
    name: grafana-server
    state: restarted
  become: true
  tags: grafana

- name: set privileges on provisioned dashboards
  file:
    path: "{{ grafana_data_dir }}/dashboards"
    recurse: true
    owner: grafana
    group: grafana
    mode: 0640
  listen: "provisioned dashboards changed"
  become: true
  tags: grafana

- name: set privileges on provisioned dashboards directory
  file:
    path: "{{ grafana_data_dir }}/dashboards"
    state: directory
    recurse: false
    mode: 0755
  listen: "provisioned dashboards changed"
  become: true
  tags: grafana

- name: reload ufw
  systemd:
    name: ufw
    state: restarted
  tags: loki
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: restarted
  tags: loki
  become: true